name: veliadash

dependencies:
  - pip
  - python>=3.8
  - pip:
    - streamlit-aggrid
    - pandas
    - ipython
    - ipykernel
    - seaborn
    - jupyterlab
    - streamlit
    - openpyxl
    - streamlit-plotly-events
    - plotly
    - scipy
    - seaborn_altair
    - jsonlines
    - py3Dmol==2.0.0.post2
    - stmol==0.0.9
    - streamlit-scrollable-textbox
    - tqdm
    - statsmodels
    - altair
    - aiobotocore
    - s3fs
    - smart_open
    - boto3
    - biopython
    - streamlit-echarts
    - pyfaidx
    - git-remote-codecommit
    - git+codecommit::us-west-2://veliadb
    - git+codecommit::us-west-2://conservation
    

    
